version: "3.1"
services:
    php:
        build: ./docker/php
        volumes:
            - ./src:/app
    nginx:
        image: nginx:1.20.2
        volumes:
            - ./src:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        ports:
            - 8080:80
    mysql:
        image: mysql:8.0-oracle
        environment:
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: demo
        volumes:
            - ./docker/data/mysql:/var/lib/mysql
    adminer:
        image: adminer:4
        links:
            - mysql
        ports:
            - 8090:8080
        environment:
            ADMINER_DEFAULT_SERVER: mysql
