version: "3.1"
services:
    php:
        build: ./docker/php
        volumes:
            - ./src:/app
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    nginx:
        image: nginx:1.20.2
        volumes:
            - ./src:/app
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
        ports:
            - 120:80
